use example;

INSERT INTO hello_world(user_name, timestamp, extension)
                    VALUES ('get_u_1001',1645728846252,
                    {'v_int':'1001', 'v_str':'"test_get"', 'v_bool':'true'});

INSERT INTO hello_world(user_name, timestamp, extension)
                    VALUES ('get_u_1001',1645728846262,
                    {'v_int':'1001', 'v_str':'"test_get"', 'v_bool':'true'});

INSERT INTO hello_world(user_name, timestamp, extension)
                    VALUES ('get_u_1003',1645728846252,
                    {'v_int':'1003', 'v_str':'"test_get"', 'v_bool':'true'});

INSERT INTO hello_world(user_name, timestamp, extension)
                    VALUES ('get_u_1004',1645728846262,
                    {'v_int':'1004', 'v_str':'"test_get"', 'v_bool':'true'});

INSERT INTO hello_world(user_name, timestamp, extension)
                    VALUES ('get_u_1004',1645728846272,
                    {'v_int':'1004', 'v_str':'"test_get"', 'v_bool':'true'});