CREATE TABLE IF NOT EXISTS WSFCONFIG
(
    NAME VARCHAR(500),
    VALUE VARCHAR(500),
    TYPE VARCHAR(150),
    DESCRIPTION VARCHAR(500),
    RW INT,
    USEDBY VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS GEOREDCONFIG
(
    NAME VARCHAR(500),
    VALUE VARCHAR(500),
    TYPE VARCHAR(150),
    DESCRIPTION VARCHAR(500),
    RW INT,
    USEDBY VARCHAR(150),
    LAST_UPDATE_TIME NUMERIC(13,0),
    PRIMARY KEY (NAME)
 );
 
DELETE FROM WSFCONFIG;
DELETE FROM GEOREDCONFIG;

INSERT INTO WSFCONFIG VALUES('config1','value1','java.lang.String','',1,'');
INSERT INTO WSFCONFIG VALUES('config2','value2','java.lang.String','',1,'');
INSERT INTO GEOREDCONFIG VALUES('georedconfig1','value1','java.lang.String','',1,'',0);
INSERT INTO GEOREDCONFIG VALUES('georedconfig2','value2','java.lang.String','',1,'',0);
