package example.exception;

public enum AppCommonErrorEnum {
	INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    TEMP_SERVICE_UNAVAILABLE("TEMP_SERVICE_UNAVAILABLE"),

    // Common
    REQUIRED_PARAMETER_MISSING("REQUIRED_PARAMETER_MISSING"),
    REQUIRED_PARAMETER_INVALID("REQUIRED_PARAMETER_INVALID"),
    PARAMETER_INVALID("PARAMETER_INVALID"),
    OPTIONAL_PARAMETER_MISSING("OPTIONAL_PARAMETER_MISSING"),

    // License
    NO_VALID_LICENSE("NO_VALID_LICENSE"),

    // client id
    INVALID_CLIENT_ID("INVALID_CLIENT_ID"),

    IAM_ACCOUNT_NOT_FOUND_ERROR("IAM_ACCOUNT_NOT_FOUND_ERROR"),
    IAM_ACCOUNT_USER_NOT_FOUND("IAM_ACCOUNT_USER_NOT_FOUND"),

    // signout
    IAM_ACCOUNT_USER_NOT_MATCH("IAM_ACCOUNT_USER_NOT_MATCH"),
    SESSION_ID_AND_USER_ID_BOTH_NULL("SESSION_ID_AND_USER_ID_BOTH_NULL"),
    IAM_SESSION_MISSING("IAM_SESSION_MISSING"),
    INVALID_IS_GLOBAL_VALUE("INVALID_IS_GLOBAL_VALUE"),


    // for SoftLock
    IAM_ACCOUNT_SOFT_LOCKED_AUTH_FAIL("IAM_ACCOUNT_SOFT_LOCKED_AUTH_FAIL"),

    // for HardLock
    IAM_ACCOUNT_HARD_LOCKED_EXCESSIVE_LOGIN("IAM_ACCOUNT_HARD_LOCKED_EXCESSIVE_LOGIN"),
    IAM_ACCOUNT_HARD_LOCKED_2ND_FACTOR("IAM_ACCOUNT_HARD_LOCKED_2ND_FACTOR"),
    IAM_ACCOUNT_HARD_LOCKED_SEC_ANSWER("IAM_ACCOUNT_HARD_LOCKED_SEC_ANSWER"),
    IAM_ACCOUNT_HARD_LOCKED_TEMP_PWD("IAM_ACCOUNT_HARD_LOCKED_TEMP_PWD"),
    IAM_ACCOUNT_HARD_LOCKED_MANUAL("IAM_ACCOUNT_HARD_LOCKED_MANUAL"),

    // for ResetPassword
    IAM_ACCOUNT_PASSWORD_RESET_LIMIT_REACHED("IAM_ACCOUNT_PASSWORD_RESET_LIMIT_REACHED"),

    // for Authenticate
    IAM_ACCOUNT_AUTHENTICATION_FAILURE("IAM_ACCOUNT_AUTHENTICATION_FAILURE"),

    // for ValidateTempPassword
    INVALID_PASSWORD_CAPTCHA_REQUIRED("INVALID_PASSWORD_CAPTCHA_REQUIRED"),
    INVALID_PASSWORD_CAPTCHA_NOT_REQUIRED("INVALID_PASSWORD_CAPTCHA_NOT_REQUIRED"),
    TEMP_PASSWORD_EXPIRED_CAPTCHA_REQUIRED("TEMP_PASSWORD_EXPIRED_CAPTCHA_REQUIRED"),
    TEMP_PASSWORD_EXPIRED_CAPTCHA_NOT_REQUIRED("TEMP_PASSWORD_EXPIRED_CAPTCHA_NOT_REQUIRED"),

    // for validate2ndFactorAnswers
    UNSUPPORTED_ANSWER_TYPE("UNSUPPORTED_ANSWER_TYPE"),

    // for ChangePassword & ValidateTempPassword
    INCORRECT_OLD_PASSWORD("INCORRECT_OLD_PASSWORD"),
    OLD_PASSWORD_NOT_FOUND("OLD_PASSWORD_NOT_FOUND"),
    INVALID_NEW_PASSWORD("INVALID_NEW_PASSWORD"),
    INCORRECT_TEMP_PASSWORD("INCORRECT_TEMP_PASSWORD"),
    INVALID_TEMP_PASSWORD("INVALID_TEMP_PASSWORD"),
    TEMP_PASSWORD_EXPIRED("TEMP_PASSWORD_EXPIRED"),
    TEMP_PASSWORD_NOT_FOUND("TEMP_PASSWORD_NOT_FOUND"),

    // for identity
    INVALID_MSISDN_FORMAT("INVALID_MSISDN_FORMAT"),
    INVALID_EMAIL_FORMAT("INVALID_EMAIL_FORMAT"),
    MSISDN_REGISTERED_TO_ANOTHER_IAM_ACCOUNT("MSISDN_REGISTERED_TO_ANOTHER_IAM_ACCOUNT"),
    MSISDN_REGISTERED_TO_ITSELF_IAM_ACCOUNT("MSISDN_REGISTERED_TO_ITSELF_IAM_ACCOUNT"),
    EMAIL_REGISTERED_TO_ANOTHER_IAM_ACCOUNT("EMAIL_REGISTERED_TO_ANOTHER_IAM_ACCOUNT"),
    EMAIL_REGISTERED_TO_ITSELF_IAM_ACCOUNT("EMAIL_REGISTERED_TO_ITSELF_IAM_ACCOUNT"),
    EXCEED_MSISDN_LINK_LIMIT("EXCEED_MSISDN_LINK_LIMIT"),
    EXCEED_EMAIL_LINK_LIMIT("EXCEED_EMAIL_LINK_LIMIT"),

    // for ValidateSecurityAnswersService
    INVALID_ANSWER("INVALID_ANSWER"),
    NO_ENOUGH_SECURITY_ANSWERS("NO_ENOUGH_SECURITY_ANSWERS"),

    // for Validate2ndFactorAnswer
    VALIDATE_2ND_FACTOR_INVALID_ANSWER("VALIDATE_2ND_FACTOR_INVALID_ANSWER"),

    // for QuerySecurityQuestion
    PARAM_CAN_NOT_EXISTED_SIMULTANEOUSLY("CAN_NOT_EXISTED_SIMULTANEOUSLY"), //TODO to be removed

    //for validation code
    INCORRECT_VALIDATION_CODE("INCORRECT_VALIDATION_CODE"),
    VALIDATION_CODE_NOT_FOUND("VALIDATION_CODE_NOT_FOUND"),

    EITHER_PARAM_MUST_EXIST("EITHER_PARAM_MUST_EXIST"),
    PARAMS_CAN_NOT_EXIST_SIMULTANEOUSLY("CAN_NOT_EXIST_SIMULTANEOUSLY"),
    ACTIVE_NUMBER_OUT_OF_RANGE("ACTIVE_NUMBER_OUT_OF_RANGE"),
    LANGUAGE_NOT_SUPPORTED_BY_QUERY_SECURITY_QUESTION("LANGUAGE_NOT_SUPPORTED_BY_QUERY_SECURITY_QUESTION"),
    SECURITY_QUESTION_NOT_FOUND("SECURITY_QUESTION_NOT_FOUND"),
    SECURITY_QUESTION_NOT_FOUND_BY_USER_IDENTIFIER("SECURITY_QUESTION_NOT_FOUND_BY_USER_IDENTIFIER"),

    // for session
    SESSION_NOT_FOUND("SESSION_NOT_FOUND"),
    INVALID_IAM_SESSION("INVALID_IAM_SESSION"),
    EXPIRED_IAM_SESSION("EXPIRED_IAM_SESSION"),

    //for unlink identity
    IDENTITY_NOT_FOUND("IDENTITY_NOT_FOUND"),
    IDENTITY_TYPE_INVALID("INVALID_IDENTITY_TYPE"),
    IDENTITY_CAN_NOT_BE_PRIMARY("PRIMARY_IDENTITY_CAN_NOT_BE_UNLINKED"),

    //address service for provioning
    ADDRESS_TYPE_EXISTED("ADDRESS_TYPE_EXISTED"),
    ADDRESS_NOT_FOUND("ADDRESS_NOT_FOUND"),

    //Service profile provisioning
    SERVICE_PROFILE_EXISTED("SERVICE_PROFILE_EXISTED"),
    SERVICE_PROFILE_NOT_FOUND("SERVICE_PROFILE_NOT_FOUND"),

    //for credential provisioning
    CREDENTIAL_EXISTED("CREDENTIAL_EXISTED"),
    CREDENTIAL_NOT_FOUND("CREDENTIAL_NOT_FOUND"),

    //for identifier provisioning
    IDENTITY_EXISTED("IDENTITY_EXISTED"),

    //for role provisioning
    ROLE_EXISTED("ROLE_EXISTED"),
    ROLE_NOT_FOUND("ROLE_NOT_FOUND"),

    //for sign out
    INVALID_REDIRECT_URI("INVALID_REDIRECT_URI"),
    
    //for black list 
    PASSWORD_MATCH_STATIC_BLACKLIST("PASSWORD_MATCH_STATIC_BLACKLIST"),
    PASSWORD_MATCH_DYNAMIC_BLACKLIST("PASSWORD_MATCH_DYNAMIC_BLACKLIST"),
    INVALID_REQUEST("INVALID_REQUEST"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    IAM_CAC_API_AUTHENTICATION_USERNAME_EMPTY("IAM_CAC_API_AUTHENTICATION_USERNAME_EMPTY"),
    EXTERNAL_PASSWORD_MATCH_STATIC_BLACKLIST("EXTERNAL_PASSWORD_MATCH_STATIC_BLACKLIST"),
    EXTERNAL_PASSWORD_MATCH_DYNAMIC_BLACKLIST("EXTERNAL_PASSWORD_MATCH_DYNAMIC_BLACKLIST"),

    // for password history
    PREVIOUS_NEW_PASSWORD("PREVIOUS_NEW_PASSWORD"),
    MATCH_PASSWORD_HISTORY("MATCH_PASSWORD_HISTORY"),

    // for test
    UNKNOWN_INTERNAL_ERROR("UNKNOWN_INTERNAL_ERROR"),

    // for IDF
    IDP_NOT_FOUND("IDP_NOT_FOUND"),
    INVALID_IDP_AUTHORIZATION_CODE("INVALID_IDP_AUTHORIZATION_CODE"),
    INVALID_FEDERATED_AUTH_REF("INVALID_FEDERATED_AUTH_REF"),
    REDIRECT_URI_NOT_FOUND("REDIRECT_URI_NOT_FOUND"),
    IDP_RETURNED_ERROR("IDP_RETURNED_ERROR"),
    INVALID_IDP_CONFIGURATION("INVALID_IDP_CONFIGURATION"),
    IDP_NOT_REACHABLE("IDP_NOT_REACHABLE"),
    USER_INFO_NOT_FOUND("USER_INFO_NOT_FOUND"),
    FEDERATION_LINKED_TO_THIS_IAM_ACCOUNT("FEDERATION_LINKED_TO_THIS_IAM_ACCOUNT"),
    FEDERATION_LINKED_TO_ANOTHER_IAM_ACCOUNT("FEDERATION_LINKED_TO_ANOTHER_IAM_ACCOUNT"),
    IAM_REQUEST_AND_SESSION_USERID_NOT_MATCH("IAM_REQUEST_AND_SESSION_USERID_NOT_MATCH"),
    ID_FEDERATION_USER_NOT_LINKED("ID_FEDERATION_USER_NOT_LINKED"),
    UNSUPPORTED_USER_ID("UNSUPPORTED_USER_ID"),
    PARAMETER_VALUE_INVALID("PARAMETER_VALUE_INVALID"),
    PARAMETER_MUST_EXIST_WHEN_ANOTHER_EXIST("PARAMETER_MUST_EXIST_WHEN_ANOTHER_EXIST"),
    SCOPE_REQUIRED("SCOPE_REQUIRED");

    private String errorCode;

    private AppCommonErrorEnum(String errorCode) {
        this.errorCode = errorCode;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }
}
